### ISSUE TITLE
Pure algebraic equation system

### ISSUE THREAD

**Issue by HeithoffM** [ikorotkin/dae-cpp#20]
Hey ikorotkin,
I'm trying to use your library to solve ODEs, DAEs, nonlinear equation systems or equation systems of unknown algebraic functions. This works well for ODEs and DAEs, but I'm running into trouble when trying to solve purely algebraic equation systems (A linear one for test case). The error I am getting is: "The time step was reduced to 9.09495e-15 but the scheme failed to converge". (There exist a solution)
Is it not possible to use the library to solve a purely algebraic equation system?
Best regards

**Comment by ikorotkin** [comment]
Hi @HeithoffM,

Technically the solver can solve purely algebraic systems as well. If the initial guess (initial condition) is not completely off (remember, the solver employs the [Newton root finding method](https://en.wikipedia.org/wiki/Newton%27s_method) to solve nonlinear systems), the solution should converge after one single time step (yes, we still have 'time' for the algebraic system, because from the solver point of view this is still a system of ODEs where all time derivatives vanished).

The error "The time step was reduced..." appears when the solver fails to converge. That means the Newton method cannot converge. Either because the initial guess is too bad, or the system does not have a solution, or Mass matrix / the RHS / Jacobian are not quite correct.

I would suggest you to try to change the initial condition (it will be the initial guess for the Newton root-finding algorithm when you solve a pure algebraic system). Then double check your Mass matrix. It should contain zero elements in the main diagonal. For example, if you have just three equations, the Mass matrix may look like

```cpp
class MyMassMatrix : public MassMatrix
{
public:
    void operator()(sparse_matrix_holder &M)
    {
        M.A.resize(3);   // 3 is the number of non-zero elements
        M.ja.resize(3);
        M.ia.resize(3);

        // Non-zero and diagonal elements
        M.A[0] = 0;
        M.A[1] = 0;
        M.A[2] = 0;

        // Column index of each element given above
        M.ja[0] = 0;
        M.ja[1] = 1;
        M.ja[2] = 2;

        // Row index of each non-zero element
        M.ia[0] = 0;
        M.ia[1] = 1;
        M.ia[2] = 2;
    }
};
```

Note we explicitly defined all diagonal elements, though they are all zero for the algebraic system.

Then check your Jacobian matrix, I would suggest you to use numerical Jacobian (provided by the solver). If it works, later you may replace it with the analytical one to significantly speed up the calculation.

If it still does not work, can you attach your test case here, or give a link? Not necessarily the whole code, just the part where you define the Mass matrix, the RHS, solver parameters you use, initial conditions, everything related to the solver.

**Comment by ikorotkin** [comment]
Sorry, forgot about one important addition.

The default time-stepping algorithm is based on the variability of the solution. If the initial guess is not very good, the algorithm may try to reduce the time step (this happened in your case). To prevent this, use stability-based time-stepping algorithm:

```cpp
    SolverOptions opt;
    opt.time_stepping = 1;
```

**Comment by HeithoffM** [comment]
Hey @ikorotkin,
I double checked every point, but I'm still getting errors.
See my code below. If it looks a little off, it is because it mostly is getting generated.
The variable `var_in` is set every "time step". The problem should correspond to the following equation system:
```math
x_0 = var_in - x_1;
x_1 = 2 * x_0;
```
and has the solution: (for var_in = 12)
```
x_0 = 1/3 * var_in;  x_0 = 4;
x_1 = 2/3 * var_in;  x_1 = 8;
```

I am relatively new to cpp, so maybe my mistake lays there...
Thank you for looking into this!


```cpp
#ifndef __MY_EQUATIONSYSTEM_1_H__
#define __MY_EQUATIONSYSTEM_1_H__

#include "solver.h"
#include "My_MassMatrix.h"
#include "My_RHS.h"

class My_EquationSystem_1 {
private:
    daecpp::state_type x;
    My_MassMatrix mass;
    My_RHS rhs;
    daecpp::Jacobian jac;
    daecpp::SolverOptions opt;
    daecpp::Solver solver;

    static daecpp::SolverOptions initOptions() {
        daecpp::SolverOptions res;
        res.time_stepping = 1;
        return res;
    }

public:
    double var_in = 12.0;

    My_EquationSystem_1() :
        x {3, 8},
        mass {},
        rhs {},
        jac {rhs, 1.0e-15},
        opt { initOptions() },
        solver {rhs, jac, mass, opt} {
    }

    void execute() {
        rhs.var_in = var_in;
        
        double t = 1.0;
        solver(x, t);
        std::cout << x[0] << "\n";
    }
};
#endif
```

```cpp
#ifndef __MY_MASSMATRIX_H__
#define __MY_MASSMATRIX_H__

#include "solver.h"

class My_MassMatrix : public daecpp::MassMatrix {
public:
    void operator()(daecpp::sparse_matrix_holder &M) {
        M.A.resize(2);
        M.A[0] = 0;
        M.A[1] = 0;

        M.ja.resize(2);
        M.ia.resize(3);
        for(MKL_INT i = 0; i < 2; i++) {
            M.ja[i] = i;
            M.ia[i] = i;
        }
        M.ia[2] = 2;
    }
};
#endif
```

```cpp
#ifndef __MY_RHS_H__
#define __MY_RHS_H__

#include "solver.h"

class My_RHS : public daecpp::RHS {
public:
    double var_in;

    void operator()(const daecpp::state_type &x, daecpp::state_type &f,
                    const double t) {
        f[0] = x[0]-(var_in-x[1]);
        f[1] = x[1]-(x[0]*2);
    }
};
#endif
```

**Comment by ikorotkin** [comment]
Hi @HeithoffM,

The code is absolutely fine, you only need to change one line, where you define the tolerance for the Jacobian matrix:

```cpp
jac {rhs, 1.0e-15},
```

In your code, the tolerance is 1.0e-15, which is too small for the double precision. When the solver estimates Jacobian numerically, it basically calculates derivatives as finite differences:

```
f(x + h) - f(x)
--------------- ,
       h
```

where `h` is the tolerance and `f` is the RHS. If `h` is very small, the difference `f(x + h) - f(x)` can become zero, or there will be too much numerical noise (floating point rounding errors). That's why, by default, `h` is 1.0e-6. You may try 1.0e-10, this should be fine too.

I also see the simulation time is equal to 1.0 in the code, so the solver will do a few time steps to reach t = 1.0. That's not necessary for the algebraic system, because we don't have time, the solver needs only one time step to converge, so you may use either `t = 0.1` in the code (because the initial time step is `dt = 0.1` by default), or set the initial time step to 1 using `res.dt_init = 1.0;`.

I just tried, it works for me! Even if I choose really bad initial conditions, like `x {300, 80},`, it still works and produces the correct answer.

**Comment by HeithoffM** [comment]
Hey @ikorotkin ,
I see, this worked for me, thank you! I think the tolerance was an artifact from previous tries.

Ok, the time variables are now also set, so the solver only does one step.

Thank you very much for you quick help.
