### ISSUE TITLE
Change RHS vector from observer conditionals

### ISSUE THREAD

**Issue by marduk-eyes** [ikorotkin/dae-cpp#30]
I've been trying to change some values used by the RHS as soon as a conditional in observer returns true, been messing around from outside daecpp source code with no success.

Is there a way to do this?

As a toy model consider a body moving through asphalt with friction coefficient mu = 0.8 and then changing the medium where it move to dirt with friction coefficient mu=0.6

**Comment by ikorotkin** [comment]
Yes, absolutely, you can pass parameters (e.g. mu) to both the RHS and observer and change them during the simulation.
A simple example of how parameters can be passed to the RHS can be found in [examples/perovskite](https://github.com/ikorotkin/dae-cpp/tree/master/examples/perovskite) folder, where we create a [structure](https://github.com/ikorotkin/dae-cpp/blob/master/examples/perovskite/perovskite_parameters.h) with parameters and then pass it to the RHS. The same data structure can be used in the observer function.

**Comment by marduk-eyes** [comment]
So i'm not quite understanding how it can't be change, I'm passing mu using a class, the problem is how I can change the MyRHS.mu value from within the observer and then pass it to MyRHS so that I can update the f[x] vector
I try passing the value by references with no success

**Comment by ikorotkin** [comment]
You can create an object of your parameter class in `main()` or inside the function where you create an instance of the RHS, Jacobian and the solver. Then pass this parameter object (as a reference) to both the RHS and the solver class with observer (and to the Jacobian class if it is analytic). So both the RHS and observer will have a reference to the same object with the parameters. If, for example, the observer changes some of the data in the parameter object, the RHS function will see the changes because it has the reference to the same object.

If this doesn't work, you may post your code here so I could double check.

**Comment by marduk-eyes** [comment]
I made it, thank you very much for the help!!!!
